### ISSUE TITLE
es6 promises and .catch

### ISSUE THREAD

**Issue by gregglind** [domenic/chai-as-promised#101]
`.eventually.throw` seems to not work right for es6 promises (Firefox 35?+).

```
var thrower = function () { throw new Error("oops") };
expect(Promise.resolve(true).then(thrower).eventually.throw()   // never called
```
Firefox's ES6 catchs all errors in then clauses to `.catch` on the promise.

**Comment by domenic** [comment]
That's how all promises work.

Can you show a full example I can run in the console (or better yet, on requirebin.com), preferably without any syntax errors?

**Comment by gregglind** [comment]
Requirebin wasn't working well for me. 

```
var thrower = function () { throw new Error("oops") };
expect(Promise.resolve(true).then(thrower)).eventually.throw()
```

**Comment by domenic** [comment]
I see the problem.

Chai's `.throw()` only works on functions. Thus, `.eventually.throw()` only works on promises for functions (i.e., promises fulfilled with functions).

You have instead a promise rejected with an Error. Since that isn't a promise fulfilled with a function, `.throw()` will not work.

**Comment by gregglind** [comment]
So what is the right work around?

**Comment by domenic** [comment]
```js
var thrower = function () { throw new Error("oops") };
expect(Promise.resolve(true).then(thrower)).eventually.rejected
```
