### ISSUE TITLE
Chai 3.0 released

### ISSUE THREAD

**Issue by Delagen** [domenic/chai-as-promised#108]
update dependencies

**Comment by keithamus** [comment]
Thanks for the issue @Delagen. Please feel free to make a PR updating the package.json and I'll happily merge it.

**Comment by danielweck** [comment]
```
The package chai does not satisfy its siblings' peerDependencies requirements!
Peer chai-as-promised@5.0.0 wants chai@>= 2.1.2 < 3
```

Culprit:
https://github.com/domenic/chai-as-promised/blob/master/package.json#L28
```json
    "peerDependencies": {
        "chai": ">= 2.1.2 < 3"
    }
```

**Comment by domenic** [comment]
Yes, indeed. Chai made a backward-incompatible change, and Chai as Promised is preventing you from using Chai as Promised with a version of Chai that it is not compatible with.

To fix this, someone needs to submit a PR updating the Chai dev-dependency and peer-dependency, showing that all the tests pass on Chai 3.0.0. (It is *not* simply a matter of changing the package.json.)

Until then, this error is correct and expected behavior.

**Comment by danielweck** [comment]
Fair enough. I've updated my `package.json` to `'chai': '^2.0.0'`.

**Comment by BobbieBarker** [comment]
I submitted a pull request for this issue, please review at your earliest convenience.

**Comment by danielweck** [comment]
@BobbieBarker did you run the unit tests to check for regression bugs? (Chai v3 is a major increment over v2, thus the risk of backward-incompatibility). See @domenic 's message above.

**Comment by keithamus** [comment]
#110 fixes this. Thanks everyone!

**Comment by danielweck** [comment]
Thanks @keithamus :)
Any ETA for NPM update? https://www.npmjs.com/package/chai-as-promised

**Comment by domenic** [comment]
Published!
