### ISSUE TITLE
Unable to assert non Error rejected promise

### ISSUE THREAD

**Issue by pveyes** [domenic/chai-as-promised#117]
From what I know, I can't assert rejected promise with object. I can assert rejectedWith using Error constructor or string, but not object. Is this the desired behavior?

Example:
```js
// moduleX.js
return Promise.reject({a: 'b'});
```

```js
// test.js
moduleX().should.be.rejectedWith({a: 'c'}); // this should fail, but it didn't
```

Currently my workaround is using this:
```js
moduleX().catch(function(resp) {
  resp.should.be.deep.equal({a: 'b'});
  done();
});
```

**Comment by keithamus** [comment]
Hey @pveyes thanks for the issue.

Short answer: You should be rejecting promises with Objects, only Errors. Promise.reject is the equivalent of throw/catch in a try/catch block. chai-as-promised will never support this, because it is an anti-pattern. Sorry.

I'll close this issue, because of the above. Feel free to continue the discussion here though :smile:.

**Comment by pveyes** [comment]
Wow I didn't know that rejecting promise with non Error is an anti-pattern, thanks for explaining @keithamus
