### ISSUE TITLE
how to test a series of promises?

### ISSUE THREAD

**Issue by Ashtonian** [domenic/chai-as-promised#141]
Hello - I'm pretty new to node, and started working with mocha/chai/chai-as-promised about two hours ago. I seem to be still learning about promises, as every time I think I understand them, I am usually wrong. I was wondering if you would be able to assist me, and I apologize for my ignorance. 

I'm trying to create some integration tests for my model. I am using a postgres promise library pg-promise, I just want to make sure the CRUD operations are all working fine. I was wondering if this is the correct way to do that? any feedback is much appreciated.  

../models/user.js
``` javascript 
var db = require('../models/db.js').conn;

var getAllSql = 'SELECT * FROM public.user';
function getAll() {
  return db.many(getAllSql);
}

var getByIdSql = 'SELECT * FROM public.user where _id = $1::uuid';

function getById(id) {
  return db.one(getByIdSql, id);
}

var insertSql = 'INSERT INTO public.User (_id,username,email,phone_number) VALUES ( ${_id}::uuid,${username},${email},${phone_number})';

function create(user) {
  return db.none(insertSql, user);
}

var deleteSql = 'DELETE from public.User where _id = $1::uuid';
function deleteById(id) {
  return db.none(deleteSql, id);

}

module.exports = {
  create: create,
  getAll: getAll,
  getById: getById,
  deleteById: deleteById,
};
```

Test:
``` javascript
var user = require('../../models/user.js');
var uuid = require('node-uuid');

function generateNewUser() {
  return {
    _id: uuid.v4(),
    username: 'testUser',
    email: '123@test.com',
    phone_number: '123456789'
  };
}

describe('user model', function() {
  it('create(), get(), deleteById() a user', function(done) {
    var userToCreate = generateNewUser();
    user.create(userToCreate).then(function() {
      return user.getById(userToCreate._id).should.eventually.become(userToCreate);
    }).then(function(results) {
      return user.getAll().should.eventually.contain(userToCreate);
    })
    .then(function(results) {
      return user.deleteById(userToCreate._id).should.eventually.be.fulfilled.notify(done);
    });
  });
});

```

**Comment by keithamus** [comment]
Thanks for the issue @Ashtonian.

You'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
