### ISSUE TITLE
Odd behavior when put eventually together with rejectedWith

### ISSUE THREAD

**Issue by yyscamper** [domenic/chai-as-promised#146]
I have found an odd behavior when putting the `eventually` together with `rejectedWith`.
Following is my assertion logic (tested in Chai-as-Promised 5.3.0, Chai 2.0.0, Mocha 2.1.0, NodeJS v0.10.25) , it will pass:
```javascript
return promise.should.eventually.be.rejectedWith(Error);   //PASS
```
If I change it to opposite logic, it will still pass!!
```javascript
return promise.should.eventually.not.be.rejectedWith(Error);  //Still PASS!!!!
```

My workaround for this is to avoid putting the `eventually` together with `rejectedWith`:
```javascript
return promise.should.be.rejectedWith(Error);
```

My expected behavior is that `eventually` should be safe to put it together with `rejectedWith`. If positive logic pass, the negative logic should fail.

**Comment by domenic** [comment]
`eventually` means: apply the following assertion to the fulfillment value of the promise.

`rejectedWith` means: assert that this promise rejects with the given value.

Combined, you have: assert that this promise fulfills with a promise that rejects with the given value.

Since promises can never fulfill with promises, this will of course never fire.

Working as intended.

**Comment by yyscamper** [comment]
Thanks @domenic , I comprehended the `eventually` as its literal meaning "finally" or "in the end".

Could you please help explain if the Promise can never fulfill with promises, then why the assertion always passes not always failed?
