### ISSUE TITLE
having an issue with resolving and rejecting $q promises

### ISSUE THREAD

**Issue by anthonyettinger** [domenic/chai-as-promised#150]
This all works fine if I use native promises, but with Angular's `$q` the chai-as-promised methods just timeout:

Here is my service method:

	  svc.test = function(foo){
	    var def = $q.defer();
	    
	    if (!foo){
	      return $q.reject(new Error('foo is required'));
	    } else {
	      // get data via ajax here...
	      // def.resolve({});
	    }

	    return def.promise;
	  };

Here is my unit test. The promise is resolved, but the `resolveValue.should.eventually....` does not work (the test just times out):

	  it.only('should error ', function(){
	    var resolvedValue = MyServices.test();
	    $rootScope.$apply();
	    return resolvedValue.should.eventually.be.rejectedWith(TypeError, 'foo is required');
	  });

**Comment by bisubus** [comment]
@anthonyettinger I think that [`transferPromiseness`](https://github.com/domenic/chai-as-promised#customizing-output-promises) does the trick:

```
chaiAsPromised.transferPromiseness = function (assertion, promise) {
  assertion.then = promise.then.bind(promise);

  inject(function ($rootScope) {
    // $q promise duck typing, Angular 1.3+
    if ('$$state' in promise && !$rootScope.$$phase) {
      $rootScope.$digest();
    }
  });
};
```

@domenic Can we add this recipe to the manual? Using Chai as promised with Angular is existing problem on the internets, no straightforward solution has been provided so far.

**Comment by domenic** [comment]
I'd rather link to a StackOverflow answer or similar so it's not something I'm responsible for maintaining, since I don't have any experience with the solution itself. E.g. "If you are trying to use Chai as Promised with Angular promises, [some people have ideas on how to do that on StackOverflow]" with the bracketed part being a link.

**Comment by bisubus** [comment]
@domenic Sure, I suppose that [this one](http://stackoverflow.com/questions/36705042/chai-as-promised-tests-dont-work-with-q-promises) should cover the issue.

I've been somewhat discouraged by the fact that there's no alternative to Angular-ish `jasmine-promise-matchers` in Mocha world, but fortunately, `chai-as-promised` is flexible enough.

**Comment by kasperlewau** [comment]
Sorry bout the necro, but `$rootScope.$digest` is not 'the way' to go about flushing asynchronous tasks in Angular. 

[`$timeout.flush`](https://docs.angularjs.org/api/ngMock/service/$timeout) is what you want, and no additional setup is necessary: 


```js
function foo () {
  return $q((resolve, reject) => {
    setTimeout(function () {
      resolve('foo');
    }, 250);
  })
}
```
```js
it('resolves with foo', () => {
  expect(foo()).to.eventually.become('foo');
  $timeout.flush();
})
```

--- 

Also, the code in the OP is not generating the expected behaviour because the expectation comes before the execution. If anything, I would add a note about that in the README. 

```js
// works!
.to.eventually.do.something();
flush(); 

// does not work!
flush();
.to.eventually.do.something();
```

**Comment by bisubus** [comment]
@kasperlewau Considering that there is 250ms `$timeout`, it is a good thing to test blackboxed `$timeout` with

```
$timeout.flush(250);
$timeout.verifyNoPendingTasks();
```

and treat `$timeout.flush` as a part of the spec.

And surprise, `$timeout.flush` won't work on `setTimeout`. `setTimeout` specs are still async and should be treated accordingly - with Jasmine `done`, or Sinon promise return, or Sinon fake timers, or Jasmine clock, or whatever. It is out of the scope of the issue, also not a concern for `chai-as-promised`.

The issue concerns *synchronous* tasks that cannot be completed because `then` callback is not fired on *fulfilled* promises until the digest is triggered manually.

**Comment by kasperlewau** [comment]
@bisubus Alright, let's scrap the timeout. 

```js
function foo (bool) {
  return $q((resolve, reject) => {
    if (bool) {
      resolve('foo!');
    } else {
      reject('boo!');
    }
  });
}
```

This will _still_ work with _the correct order of execution_. You don't have to involve the `done` callback when using chai-as-promised. That's the beauty of it as far as I'm concerned. 

As soon as you start using chai-as-promised w/ Angular and you **dont** want to involve the `done` callback, you need to switch positions of your expectation & execution. That is it. 

> The issue concerns synchronous tasks that cannot be completed because then callback is not fired on fulfilled promises until the digest is triggered manually.

You will (and should) always need to trigger a `$digest` cycle in your tests. If the code under testing depends on that sort of stuff. `$q` promises, does.

I'm going to disregard from the $timeout best practices for now, feels like that's besides the point. 

We can continue this on StackOverflow, if need be.

**Comment by bisubus** [comment]
@kasperlewau If there are no non-Angular asynchronous operations like `setTimeout`, the spec is synchronous then.

Calling `$rootScope.$digest()` in `transferPromiseness` hook saves the one from calling it after each `expect...eventually`. To make the hook workable when accidentally calling `expect...eventually` on digests (namely, inside another `then` callback), it should be foolproofed with

    $rootScope.$$phase || $rootScope.$digest();

I guess it's as simple as that.

**Comment by benitogf** [comment]
Hi sorry about bump again, I tried using the solutions provided by the link on the readme and here, but it's not looking good, made a [plunker](http://plnkr.co/edit/2bSLFDpyDQyzYIJsXjfB?p=preview) with examples that would be nice to have documented imho
