### ISSUE TITLE
Problems with .notify(done)

### ISSUE THREAD

**Issue by tamj0rd2** [domenic/chai-as-promised#204]
I'm using Jest which comes with create-react-app. I've written the below test:

```js
it('resolves to false', done => {
  let promise = Promise.resolve(true)
  expect(promise).to.be.fulfilled.then(result => {
    expect(result).to.equal(false)
  }).and.notify(done)
})
```

I know I can resolve this by making the promise resolve to true, but ideally I'd like the test to fail rather than completely stopping the test runner. Reason being, if a value in the actual code I'm testing happens to be incorrect, I don't want the test runner to stop working each time I try to test it. I just want it to fail the test. Is there a way around this?

Here's the output that I get from the test runner on failure:
```
/mnt/Storage/Coding/portfolio/node_modules/react-scripts/scripts/test.js:22
  throw err;
  ^
AssertionError: expected true to equal false
    at to.be.fulfilled.then.result (/mnt/Storage/Coding/portfolio/src/__tests__/Contact.test.js:292:38)
npm ERR! Test failed.  See above for more details.
```

If I use the should syntax instead, the test passes even though the assertion is wrong. I'm using chai 3.5

**Comment by tamj0rd2** [comment]
I forgot to return the expect.

**Comment by tamj0rd2** [comment]
Using .notify(done) seems to pass all tests regardless of whether or not the assertions were correct

**Comment by meeber** [comment]
@tamj0rd2 I don't know anything about Jest but I'm going to guess it doesn't support passing an error to the `done` callback in the same way that Mocha does, so the `.should.notify(done)` variation of what you're trying to do wouldn't work. Using Mocha, the `.should.notify(done)` behaves correctly. I copied and pasted your example with no modifications which correctly resulted in "AssertionError: expected 2 to equal 3":

```js
it('this test should fail because 1+1 != 3', done => {
  let promise = Promise.resolve(1 + 1)
  promise.should.be.fulfilled.then((result) => {
    console.log(result) // outputs 2 as expected
    result.should.equal(3) // maybe this passes in Jest but not in Mocha
  }).should.notify(done)
})
```

Also, it's no surprise that your other example below doesn't work properly in any test runner; the `done()` would never be called if the line before it caused an error, and the promise would swallow the error. The test runner would never know the test completed, and it'd eventually time out.

```
it('this test should fail because 1+1 != 3', done => {
  let promise = Promise.resolve(1 + 1)
  expect(promise).to.be.fulfilled.then(result => {
    console.log(result) // outputs 2 as expected
    result.should.equal(3) // this assertion fails and the entire test runner gets stopped
    done()
  })
})
```

To get around this problem you could add `.catch(done)` to the end of the promise chain. But if your test runner supports it, then I strongly recommend just returning the promise instead of using a `done` callback.

**Comment by domenic** [comment]
Sounds like there's some solid advice here. Definitely don't both return and use done(). Maybe if we can confirm Jest's done() doesn't work well, we can add a warning about it to the readme. But until then, closing.
