### ISSUE TITLE
Unclear docs

### ISSUE THREAD

**Issue by PFight** [domenic/chai-as-promised#230]
I new to chai, and for me were a problem to adopt chai-as-promised. I have spent hours before found [this article](https://medium.com/earnest-engineering/testing-promise-rejections-with-chai-as-promised-c65c7c33f329). Only there I have finally found, how to write promise-based expect like this:

    it('find should throw if not loaded', async () => {
      const services = { storage: new StorageMock({}) };
      let service = new Services.ProductService(services);
      expect(service.find(testProd.id.get()))
        .to.be.rejected;
    });

I looked at [this docs](http://chaijs.com/plugins/chai-as-promised/), and next things were unclear:

1) I hurried, and not listed down to Installation part. I tried just import, import instead of chai, etc. before called chai.use.
2) There is no syntax example for `expect` check to rejection. There is [next one](http://chaijs.com/plugins/chai-as-promised/#how-to-use):

        promise.should.be.rejected;

   So, I tried (not working):
 
        expect(service.find(testProd.id.get()))
             .should.be.rejected; 
       service.find(testProd.id.get())
             .should.be.rejected
       // docs says: "other variants of Chai's `throw` assertion work too" - nothing
        expect(() => service.find(testProd.id.get()))
             .throw(); 

   But the right syntax was

         expect(service.find(testProd.id.get()))
             .to.be.rejected;

    How can I determine this? Is it obviuous for experienced chai user?

**Comment by keithamus** [comment]
Hey @PFight thanks for the issue.

If you're using `async` functions, you need to either `await` on the value, or `await` on the assertion. Your test should look like this:

```js
it('find should throw if not loaded', async () => {
  const services = { storage: new StorageMock({}) };
  let service = new Services.ProductService(services);
  await (expect(service.find(testProd.id.get())).to.be.rejected);
});
```

Alternatively you can return the Promise back to your test runner; even when not using `async` functions:

```js
it('find should throw if not loaded', () => {
  const services = { storage: new StorageMock({}) };
  let service = new Services.ProductService(services);
  return expect(service.find(testProd.id.get())).to.be.rejected;
});
```

Just FYI, for questions like this you'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.

**Comment by pro-src** [comment]
I really don't understand how you ***completely*** failed to understand his question. English obviously isn't his first language. Is it yours? I can't tell.
