### ISSUE TITLE
4.3.1 breaks compatibility with chai@1.10.0

### ISSUE THREAD

**Issue by Sanjo** [domenic/chai-as-promised#96]
Since chai-as-promised@4.3.1 the result output of cuked is broken. chai-as-promised@4.3.0 works fine.

### Reproduce

```bash
git clone https://github.com/eclifford/cuked.git
cd cuked
npm install
cd example
../bin/cuked
```

#### It should output

```
....
1 scenario (1 passed)
3 steps (3 passed)
```

#### Instead it outputs
```
..
```

chai-as-promised is only used in this file: https://github.com/eclifford/cuked/blob/master/lib/cucumberjs/world.js

CC: @eclifford

**Comment by Sanjo** [comment]
Upgrading chai to 2.1.2 from (1.10.0) also fixes the issue. So that means that chai-as-promised@4.3.1 broke compatibility with chai@1.10.0.

**Comment by domenic** [comment]
Ah thanks, I will unpublish 4.3.1 and publish 4.3.2 with an updated peer dependency.

**Comment by leoselig** [comment]
We had major problems today with all of our test projects after your upgrade
I think patch updates should **never** require a major version upgrade of peer dependencies (in this case chai) - this broke our test systems today
Even removing removing the "^x.y.z" patch policy wouldn't have helped temporarily since you unpublished
This seems to violate SemVer completely and makes your package unusable for stable systems

**Comment by domenic** [comment]
OK, let's unpublish 4.3.2 then

**Comment by leoselig** [comment]
I think you should never unpublish
revert to the state of 4.3.0 and publish it as 4.3.3
otherwise saved dependencies on 4.3.1 or 4.3.2 might fail

**Comment by domenic** [comment]
Can't make anyone happy these days. Gonna go do something else for a week or so.

**Comment by kkamperschroer** [comment]
I appreciate your hard work @domenic. Our build may have been broken for a few minutes, but it was easy enough to track down. Thanks for resolving this so quickly.

**Comment by trodrigues** [comment]
Yeah, publishing a newer version with the older state would've been a better idea. We just got some broken builds because of this and it had me scratching my head for a while (specially because I thought the unpublish ability had been removed from the npm client).

**Comment by leedm777** [comment]
FWIW, the SemVer offender is chai v1.10.0. It accidentally introduced a breaking change, which [was reverted in 2.0.0](https://github.com/chaijs/chai/blob/master/ReleaseNotes.md#200--2015-02-09).

Since chai v1.10.0 was a SemVer violation, I recommend avoiding it. Either stick with chai v1.9.x, or upgrade to chai v2.x.

The cuked example in the issue report works fine with chai v1.9.2, and chai v2.2.0. It only fails with v0.10.0

```bash
$ git clone https://github.com/eclifford/cuked.git
$ cd cuked
$ npm install
$ npm install domenic/chai-as-promised # install chai-as-promised from master

$ npm install chai@1.9.2 # works
$ ( cd example/ && ../bin/cuked )
....

1 scenario (1 passed)
3 steps (3 passed)

$ npm install chai@1.10.0 # fails
$ ( cd example/ && ../bin/cuked )
..

$ npm install chai@2.2.0 # works
$ ( cd example/ && ../bin/cuked )
....

1 scenario (1 passed)
3 steps (3 passed)
```
