### ISSUE TITLE
Returning the result of `.should.be.rejected` leads to output on stderr.

### ISSUE THREAD

**Issue by nuisanceofcats** [domenic/chai-as-promised#97]
I would have thought this mocha test would work fine:
```javascript
  // Either I've made a mistake or chai-as-promised is crap...
  it('finds that chai-as-promised is not broken', function() {
    var Promise = require('bluebird')
    var promise = Promise.reject('oh')
    return promise.should.be.rejected
  })
```

It looks like it passes but check out the stderr after the test...

```
  User Model
    ✓ finds that chai-as-promised is not broken 
Unhandled rejection Error: oh
    at Object.ensureErrorObject (/home/mega-totoro/projects/cuddle-friends/node_modules/bluebird/js/main/util.js:226:20)
    at Promise._rejectCallback (/home/mega-totoro/projects/cuddle-friends/node_modules/bluebird/js/main/promise.js:416:22)
    at new Promise.reject.Promise.rejected (/home/mega-totoro/projects/cuddle-friends/node_modules/bluebird/js/main/promise.js:179:9)
    at Context.<anonymous> (/home/mega-totoro/projects/cuddle-friends/server/api/user/user.model.spec.js:40:19)
    at callFn (/home/mega-totoro/projects/cuddle-friends/node_modules/grunt-mocha-test/node_modules/mocha/lib/runnable.js:223:21)
```

Or am I doing something stupid?

**Comment by domenic** [comment]
This is a Bluebird bug/"feature", your tests are fine, but they have strange policies that result in garbage on stderr when promises are being used in ways the author of Bluebird did not anticipate.

**Comment by nuisanceofcats** [comment]
Thanks for the info.

**Comment by adambiggs** [comment]
Any recommendations on how to prevent this with Bluebird?

**Comment by ohjames** [comment]
@adambiggs I gave up on it so I can only recommend "don't use chai-as-promised"

**Comment by keithamus** [comment]
That advice could just as easily be "don't use bluebird" :wink:

**Comment by ohjames** [comment]
After relying on all that cool stuff like `Promise.reduce` `thenReturn` etc. etc. it's too hard to remove it. And doing so just for a tiny test framework. It's a shame this tool doesn't support the "best" promise library.

**Comment by domenic** [comment]
It supports it just fine. Bluebird has some bugs that cause random shit to be spewed onto the console. That's a bug, but not a fatal one, and it's not Chai as Promised's job to fix it.

**Comment by ohjames** [comment]
I'm pretty sceptical of your assertion there, where's the link to the bluebird bug? How come the thousands of projects that use bluebird haven't come across the same thing?

**Comment by domenic** [comment]
It's not my responsibility to file a bug on a library I'm not using.

This is a pretty commonly encountered issue with Bluebird; see e.g. http://lmgtfy.com/?q=bluebird+%22Unhandled+rejection%22

Anyway this is pretty clearly turning into something combative and non-productive, and there's no Chai as Promised issue here, so I'm locking this thread.

**Comment by keithamus** [comment]
Just FYI @ohjames - this isn't Chai As Promised's bug - because the [rejected property](https://github.com/domenic/chai-as-promised/blob/master/lib/chai-as-promised.js#L120-L142) handles the rejection ([right about here](https://github.com/domenic/chai-as-promised/blob/master/lib/chai-as-promised.js#L130-L138)), so Bluebird saying this is an unhandled rejection is false. It has been handled, very explicitly. 

Also, I've filed petkaantonov/bluebird#695 on your behalf. Hopefully you don't mind - and hopefully this can lead to bluebird fixing the issue on their side.

Lastly I'd also kindly ask you refrain from second guessing the maintainers of open source projects without concrete proof otherwise - not only is it not productive to solving the issue, but the maintainers are very busy, and unless they have masochistic tendencies like I do, cannot spend their time dealing with every comment. I know you can't reply here, but if you feel the need to discuss this further you can reach me on twitter [@keithamus](http://twitter.com/keithamus).
